### PR TITLE
Fix: issue #186

### LINKED ISSUE #186: Fix horizontal scroll
the `.w-screen` class on the header produces a tiny bit of extra width space that makes the page scroll-able horizontally. 

platform: Firefox 124 on Linux

### PR DESCRIPTION
**Pull request by sudanchapagain**
Fixes #186 

## Proposed Changes

  -
  -
  -

### CODE REVIEW

**Comment by sudanchapagain** [comment]
I didn't this could happen.

**Comment by sreetamdas** [comment]
@sudanchapagain sorry I didn't quite understand you; I've approved the deployment. Could you check and confirm if this solves the issue for you (on Windows)? I'll do the same for MacOS as well. :)

**Comment by sudanchapagain** [comment]
Yes, fixed. 

> I didn't this could happen.

I meant to write, "I didn't *know* this could happen." but missed the *know* and by that i meant, i deleted the forked repo from my account and it said it closed this PR because i deleted the head repository.

**Comment by sreetamdas** [comment]
@sudanchapagain that's alright, you should be able to reopen the PR by pushing the same changes to this branch once more.

**Comment by sreetamdas** [comment]
Test

**Comment by sudanchapagain** [comment]
I don't seem to be able to reopen this.

**Comment by sreetamdas** [comment]
@sudanchapagain sorry, not sure why that's happening. Could you confirm if the original issue if fixed for you here: https://sreetamdas-com-git-fork-sudanchapagain-main-sreetamdas-projects.vercel.app

**Comment by sudanchapagain** [comment]
yes. Fixed in this deployment.

**Pull request closed without merging**
