### PR TITLE
chore:  ♿ add `aria-current: page` attribute to active link.

### LINKED ISSUE #41: Improve accessibility
Open ended issue—all improvements are welcome!

### PR DESCRIPTION
**Pull request by hussamkhatib**
Fixes #41 

## Proposed Changes
  - [add `aria-current: page` attribute to active link.](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-current)

### CODE REVIEW

**Comment by sreetamdas** [comment]
Sorry for having missed this @hussamkhatib 😅 
I like this addition, can I reopen it?

**Comment by hussamkhatib** [comment]
Sure.
I closed it as I am not sure if it is the proper usage of that attribute.
> No aria is better is than bad aria  



>When you have a group of related elements, such as several links in a breadcrumb or steps in a multi-step flow, with one element in the group styled differently from the others to indicate to the sighted user that this is the current element within its group, the aria-current should be used to inform the assistive technology user what has been indicated via styling.
[mdn](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-current)

I also created a post on [Reddit](https://www.reddit.com/r/accessibility/comments/tawuhk/should_we_only_use_ariacurrent_page_in_a/i03piz9/?context=3), didn't get the answer I was expecting.

**Comment by sreetamdas** [comment]
@hussamkhatib Hmmm, well first of all, thanks so much for going ahead and posting about this on Reddit 🙌 That's pretty impressive.

Secondly, I think this is a good addition and fits here with #41 — but we should also include a visual marker on the Navbar to indicate what the current page is. I can work on this, and then we can reopen and merge your PR here? What do you think?

**Comment by hussamkhatib** [comment]
Sounds good.

**Pull request closed without merging**
