### PR TITLE
chore: :wheelchair: Added title/label for stat icons

### LINKED ISSUE #41: Improve accessibility
Open ended issue—all improvements are welcome!

### PR DESCRIPTION
**Pull request by hinogi**
ref #41

Fixes #41

## Proposed Changes

  - Added title and labels for stat icons
  -
  -

### CODE REVIEW

**Comment by sreetamdas** [comment]
Thanks so much @hinogi! I never realised I overlooked this — let me know when you're ready for this to be merged 😄

**Comment by hinogi** [comment]
> 
> 
> Thanks so much @hinogi! I never realised I overlooked this — let me know when you're ready for this to be merged 😄

I was trying to also add `role="main"` to `Main` but that doesn't seem to work.

**Comment by sreetamdas** [comment]
Sorry, I didn't understand, where did you want to add `role="main"` to?

**Comment by hinogi** [comment]
> 
> 
> Do you mean here? https://github.com/sreetamdas/sreetamdas.com/blob/main/src/pages/_document.tsx#L62

Exactly

**Comment by sreetamdas** [comment]
Ah, I'm not sure if you're familiar with [Next.js](https://nextjs.org/docs/advanced-features/custom-document) but that doesn't need an alt text 😄 

Lemme know when you're ready to merge this!

**Pull request merged**
